### ISSUE TITLE
export package's own vfile and other sub-dependencies

### ISSUE THREAD

**Issue by zipang** [vfile/vfile-find-down#3]
## Feature request

It would be awesome if packages like `vfile-find-down`, `vfile-find-up`, `to-vfile` and consorts all did expose their own version of the `vfile` package.

This way, i could reference only one package in my `package.json`, relying on him to load and expose the others, and not have to maintain possible divergent and incompatible versions of these packages.

And.. and and.. it would allow me to extend `VFile.prototype` in a way that would work _across all of these packages_ ! Because right now it is not at all possible as i have several instances of the vfile package inside several `node_modules/` subfolders !

### Usage example
pseudo-code (dream code) not working but you'll see the point..

```js
// import everything from one unique package !
const { all, VFile, toVfile } = require('vfile-find-down')

// let's extend VFile proto with a custom .is() method
// that accepts a string, a Function or an array of all these
VFile.prototype.is = (what) => {
    if (typeof what === 'string') {
      return (this.basename === what) || (this.extname === what)
    } else if (typeof what === 'function') {
      return what(this)
    } else if (Array.isArray(what)) {
      let passed = what.find(unary => vfile.test(unary))
      return passed !== undefined
    }
}

// Now any vfile object created _by any_ of these package can benefit from the .is() custom method
var file1 = new Vfile({ path: '/content/README.md' })
var file2 = toVfile('/path/to/myfile.txt')
var files = await all(() => true, '/content')

file1.is('.md') // => TRUE
file2.is(['.txt', '.md']) // => TRUE
files[0].is(...) // => whatever the result is..

```

**Comment by wooorm** [comment]
See vfile/to-vfile#8.
